/*
 * tableid.h 
 *
 */

/*************************************************************
 *!            !!!!!! DO NOT MODIFY THIS FILE !!!!!!    !!!!!*
 *!!             THIS FILE IS GENERATED BY BUILDRES      !!!!*
 *!!!         THE METADATA FOR THIS FILE IS IN THE SQL    !!!*
 *!!!!       SERVER, SO DO NOT TOUCH IT, OR THE CLIENT     !!*
 *!!!!!    VERSIONS OF THE SOFTWARE WILL BE OUT OF WACK!!   !*
 *************************************************************
 *                                                           *
 * Id's for column and table names are system generated.     *
 * You couldn't change them if your life depended on it.     *
 * Don't even try.  If you do, AASHTO will haunt you for     *
 * the rest of your life.                                    *
 * Therefore, if the column or table ID's have been changed  *
 * all resources that use column and table ID's should be    *
 * remade, and fresh copies have to be sent to everyone and  *
 * their immediate relatives MUST be sent a new copy of all  *
 * executables, as well as a sever SQL server data base      *
 * update.  See, you didn't really want to change that ID,   *
 * did you?                                                  *
 *************************************************************/





#define tApplication                          1
#define tApplicationCatalog                   2
#define tApplicationDisabled                117
#define tApplicationReport                    3
#define tArea                                 4
#define tAreaAdjustment                       5
#define tAreaCounty                           6
#define tAreaType                             7
#define tBaseDate                             8
#define tBreakdownEstimationMethod            9
#define tCatalog                             11
#define tCodeTable                           12
#define tCodeValue                           13
#define tColumns                             14
#define tCostBasedEstimate                   15
#define tCostSheet                           16
#define tCounty                              17
#define tCountyMap                           18
#define tCrew                                19
#define tCrewEquipment                       20
#define tCrewEquipmentUsed                   21
#define tCrewLabor                           22
#define tCrewLaborUsed                       23
#define tCrewUsed                            24
#define tCurrentSpecYear                    123
#define tDatabaseRelease                    118
#define tDefaultJobUser                      25
#define tDefaultProgramUser                  26
#define tEquipment                           28
#define tEquipmentRate                       29
#define tExportInfo                         119
#define tFacilityMaterial                    30
#define tFund                                31
#define tHistoricalBidder                    32
#define tHistoricalItemBid                   33
#define tHistoricalProject                   34
#define tHistoricalProjectCategory           35
#define tHistoricalProjectItem               36
#define tHistoricalProposal                  37
#define tHistoricalProposalItem              38
#define tHistoricalProposalMajorItem         39
#define tInflationChange                     40
#define tInflationPrediction                 41
#define tItemEstimationMethod                42
#define tJob                                 43
#define tJobAlternate                        44
#define tJobAlternateGroup                   45
#define tJobBreakdown                        46
#define tJobBreakdownFund                    47
#define tJobBreakdownMajorItem               48
#define tJobBreakdownProfile                 49
#define tJobComment                          50
#define tJobCostBasedEstimate                51
#define tJobCostSheet                        52
#define tJobCrewEquipmentUsed                53
#define tJobCrewLaborUsed                    54
#define tJobCrewUsed                         55
#define tJobFund                             56
#define tJobItem                             57
#define tJobItemDependency                   58
#define tJobItemProjectItem                  59
#define tJobMaterialUsed                     60
#define tJobProject                          61
#define tJobUser                             62
#define tJobZone                             63
#define tKeyMaster                           64
#define tLabor                               65
#define tLaborerWageAndBenefits              66
#define tLongText                            67
#define tMajorItem                           68
#define tMajorItemPriceAdjustment            69
#define tMajorItemPriceRegression            70
#define tMajorItemPriceVariable              71
#define tMajorItemQuantityAdjustment         72
#define tMajorItemQuantityRegression         73
#define tMajorItemQuantityVariable           74
#define tMap                                 75
#define tMapVertex                           76
#define tMaterial                            77
#define tMaterialPrice                       78
#define tMaterialUsed                        79
#define tPEMETHAverage                       81
#define tPEMETHRegression                    82
#define tParametricProfile                   83
#define tProgram                             84
#define tProgramFund                         85
#define tProgramJob                          86
#define tProgramJobDependency                87
#define tProgramUser                         88
#define tProject                             89
#define tProjectCategory                     90
#define tProjectItem                         91
#define tReport                              92
#define tSeasonAdjustment                    93
#define tSignificantMajorItem                94
#define tStandardItem                        95
#define tStandardItemDependency              96
#define tStandardItemMajorItem               97
#define tStandardItemPEMETHAverage          120
#define tStandardItemPEMETHRegression       121
#define tStdItemDefaultPrices                98
#define tTables                              99
#define tTablesColumns                      100
#define tTask                               101
#define tUnitTypeSystem                     122
#define tUser                               102
#define tUserApplication                    103
#define tUserCatalog                        104
#define tUserMessage                        116
#define tVendor                             105
#define tVendorAddress                      106
#define tVendorClassification               107
#define tVendorFacility                     108
#define tWeightedAverageUnitPrice           109
#define tWorkTypeAdjustment                 110
#define tWorkingDayCalendar                 115
#define tWorkingDayPrediction               111
#define tZone                               112
#define tZoneMap                            113
#define tZoneType                           114
