/*
 * colid.h 
 *
 */

/*************************************************************
 *!            !!!!!! DO NOT MODIFY THIS FILE !!!!!!    !!!!!*
 *!!             THIS FILE IS GENERATED BY BUILDRES      !!!!*
 *!!!         THE METADATA FOR THIS FILE IS IN THE SQL    !!!*
 *!!!!       SERVER, SO DO NOT TOUCH IT, OR THE CLIENT     !!*
 *!!!!!    VERSIONS OF THE SOFTWARE WILL BE OUT OF WACK!!   !*
 *************************************************************
 *                                                           *
 * Id's for column and table names are system generated.     *
 * You couldn't change them if your life depended on it.     *
 * Don't even try.  If you do, AASHTO will haunt you for     *
 * the rest of your life.                                    *
 * Therefore, if the column or table ID's have been changed  *
 * all resources that use column and table ID's should be    *
 * remade, and fresh copies have to be sent to everyone and  *
 * their immediate relatives MUST be sent a new copy of all  *
 * executables, as well as a sever SQL server data base      *
 * update.  See, you didn't really want to change that ID,   *
 * did you?                                                  *
 *************************************************************/





#define cAccessPrivilege                      1
#define cActive                               2
#define cAddress                              3
#define cAddressSequenceNumber                4
#define cAdjustment                           5
#define cAlternate                            6
#define cAlternateGroup                       7
#define cAmountFunded                         8
#define cAnnualInflation                      9
#define cApplicationID                       10
#define cApplicationKey                      11
#define cApprovedBy                          12
#define cArchiveCopyFileName                 13
#define cAreaID                              14
#define cAreaKey                             15
#define cAreaTypeID                          16
#define cAreaTypeKey                         17
#define cAveragePavementDepth                18
#define cAveragePavementWidth                19
#define cAwardedAmount                       20
#define cAwardedBidTotal                     21
#define cAwardedBidderKey                    22
#define cBaseCoefficient                     23
#define cBaseDate                            24
#define cBaseUnitPrice                       25
#define cBidTotal                            26
#define cBreakdownEstimationMethod           27
#define cBreakdownEstimationMethodID         28
#define cBreakdownEstimationMethodKey        29
#define cCapacity                            30
#define cCatalogID                           31
#define cCatalogKey                          32
#define cCategory                            33
#define cCategoryNumber                      34
#define cCertification                       35
#define cChangeDate                          36
#define cCheckedBy                           37
#define cChosenAlternateKey                  38
#define cCity                                39
#define cCodeFile                            40
#define cCodeTableID                         41
#define cCodeTableKey                        42
#define cCodeValueID                         43
#define cCodeValueKey                        44
#define cColumnKey                           45
#define cColumnName                          46
#define cComment                             47
#define cCommentDate                         48
#define cCommentTime                         49
#define cCommonUnit                          50
#define cConstructionEngineeringPct          51
#define cContingencyPercent                  52
#define cCostBasedEstimateID                 53
#define cCostBasedEstimateKey                54
#define cCostSheetCrewID                     55
#define cCostSheetCrewKey                    56
#define cCostSheetID                         57
#define cCostSheetKey                        58
#define cCountyID                            59
#define cCountyKey                           60
#define cCountyName                          61
#define cCrewID                              62
#define cCrewKey                             63
#define cCrossSectionAdjustment              64
#define cDBEClassification                   65
#define cDate                               292
#define cDateApproved                        66
#define cDateChecked                         67
#define cDateClosed                          68
#define cDateComplete                        69
#define cDateCreated                         70
#define cDateOpened                          71
#define cDavisBaconOvertimeRate              72
#define cDavisBaconRate                      73
#define cDavisBaconWages                     74
#define cDaysElapsedBeforeStart              75
#define cDefaultHoursPerDay                  76
#define cDefaultProductionRate               77
#define cDefaultStartTime                    78
#define cDefaultValue                        79
#define cDelay                               80
#define cDeleted                            293
#define cDepthAdjustment                     81
#define cDescription                         82
#define cDetailedEstimate                    83
#define cDetailedEstimateCost                84
#define cDisplayedProductionRate            299
#define cDistrict                            85
#define cDllName                            294
#define cDuration                            86
#define cEndDate                             87
#define cEngineersEstimate                   88
#define cEquipmentDailyCost                  89
#define cEquipmentID                         90
#define cEquipmentKey                        91
#define cEquipmentOverheadPct                92
#define cEstimate                            93
#define cEstimateTotal                       94
#define cEstimateTotalAdjForInflation        95
#define cEstimatedAmount                     96
#define cEstimatedCost                       97
#define cEstimationComment                   98
#define cEstimationMethodAbbreviation        99
#define cEstimator                          100
#define cExtendedAmount                     101
#define cFacilityNumber                     102
#define cFifthPercentile                    103
#define cFiftiethPercentile                 104
#define cFromUserKey                        288
#define cFunctionName                       295
#define cFundID                             105
#define cFundKey                            106
#define cHoursPerDay                        107
#define cImportDate                         108
#define cInflationPredictionID              109
#define cInflationPredictionKey             110
#define cInflationRate                      111
#define cInitialPrediction                  112
#define cItemEstimationMethodID             113
#define cItemEstimationMethodKey            114
#define cItemKey                            115
#define cItemNumber                         298
#define cJobAlternateGroupID                116
#define cJobAlternateGroupKey               117
#define cJobAlternateID                     118
#define cJobAlternateKey                    119
#define cJobBreakdownID                     120
#define cJobBreakdownKey                    121
#define cJobCostSheetKey                    122
#define cJobCrewKey                         123
#define cJobID                              124
#define cJobItemCostBasedEstimateKey        125
#define cJobItemKey                         126
#define cJobKey                             127
#define cKeyValue                           128
#define cLaborDailyCost                     129
#define cLaborOverheadPct                   130
#define cLaborerID                          131
#define cLaborerKey                         132
#define cLag                                133
#define cLastUpdate                         134
#define cLength                             135
#define cLettingDate                        136
#define cLettingMonth                       137
#define cLineNumber                         296
#define cLink                               138
#define cLocation                           139
#define cLocationDescription                140
#define cLongDescription                    141
#define cLongEstimationComment              142
#define cLongText                           143
#define cLongTextKey                        144
#define cLowBidAmount                       145
#define cLowBidTotal                        146
#define cLowBidderKey                       147
#define cLowCostAlternate                   148
#define cLumpSum                            149
#define cMajorItemID                        150
#define cMajorItemKey                       151
#define cMapID                              152
#define cMapKey                             153
#define cMarkUpPct                          154
#define cMaterialID                         155
#define cMaterialKey                        156
#define cMaterialQuantityAdjustment         157
#define cMaterialsOverheadPct               158
#define cMaterialsUnitCost                  159
#define cMaximumCodeLength                  160
#define cMaximumQuantity                    161
#define cMedianQuantity                     162
#define cMedianQuantityUnitPrice            163
#define cMessage                            289
#define cMessageKey                         291
#define cMinimumQuantity                    164
#define cMonth                              165
#define cName                               166
#define cNinetyFifthPercentile              167
#define cNonDavisBaconOvertimeRate          168
#define cNonDavisBaconRate                  169
#define cNumberOfBids                       170
#define cOvertimeHoursPerDay                171
#define cOvertimeRate                       172
#define cPassword                           173
#define cPavementDepth                      174
#define cPavementWidth                      175
#define cPercentComplete                    176
#define cPercentFunded                      177
#define cPercentofCost                      178
#define cPercentofValue                     179
#define cPercentofValueLock                 180
#define cPermission                         181
#define cPhoneNumber                        182
#define cPortableFlag                       183
#define cPredecessorItemKey                 184
#define cPredecessorJobItemKey              185
#define cPredecessorJobKey                  186
#define cPreliminaryEstimateCost            187
#define cPriceAdjustment                    188
#define cPrimaryCountyKey                   189
#define cPriority                           190
#define cProductionAdjustment               191
#define cProductionGranularity              192
#define cProductionMethod                   193
#define cProductionRate                     194
#define cProfileID                          195
#define cProfileKey                         196
#define cProgramID                          197
#define cProgramKey                         198
#define cProjectControlNumber               199
#define cProjectKey                         200
#define cProjectNumber                      201
#define cProposalID                         202
#define cProposalItemKey                    203
#define cProposalKey                        204
#define cProposalLength                     205
#define cQualitativeValue                   206
#define cQualitativeVariable                207
#define cQuantity                           208
#define cQuantityAdjustment                 209
#define cQuantityConversionFactor           210
#define cQuantityLevel                      211
#define cQuantityLock                       212
#define cQuantityPerItemUnit                213
#define cRate                               214
#define cReason                             215
#define cRejectedFlag                       216
#define cReportID                           217
#define cReportKey                          218
#define cRoadType                           219
#define cRoundingPrecision                  220
#define cSeason                             221
#define cSequenceNumber                     222
#define cSeventyFifthPercentile             223
#define cShortDescription                   224
#define cShortName                          225
#define cShortText                          226
#define cSlack                              227
#define cSpecYear                           228
#define cStandardItemKey                    229
#define cStandardItemNumber                 230
#define cStartDate                          231
#define cState                              232
#define cStateApproved                      233
#define cStatus                             234
#define cStructure                          235
#define cStructureAreaAdjustment            236
#define cStructureBaseAdjustment            237
#define cStructureID                        238
#define cStructureLength                    239
#define cStructureLengthAdjustment          240
#define cStructureType                      241
#define cStructureWidth                     242
#define cStructureWidthAdjustment           243
#define cSuccessorItemKey                   244
#define cSuccessorJobItemKey                245
#define cSuccessorJobKey                    246
#define cSupplementalDescription            247
#define cTableKey                           248
#define cTableName                          249
#define cTaskDescription                    250
#define cTaskID                             251
#define cTaskKey                            252
#define cTime                               290
#define cToUserKey                          287
#define cTotalAdjustedForInflation          253
#define cTotalCost                          254
#define cTranslation                        255
#define cTwentyFifthPercentile              256
#define cType                               257
#define cUnit                               258
#define cUnitPrice                          259
#define cUnitPriceLock                      260
#define cUnitSystem                         301
#define cUnitType                           300
#define cUrbanRuralClass                    261
#define cUserGrantedPrivilege               262
#define cUserID                             263
#define cUserKey                            264
#define cVariableValue                      265
#define cVendorAddressKey                   286
#define cVendorClassification               266
#define cVendorID                           267
#define cVendorKey                          268
#define cVersion                            297
#define cVertex                             269
#define cVertexOrder                        270
#define cWeightedAverageUnitPrice           271
#define cWidth                              272
#define cWidthAdjustment                    273
#define cWorkBeginDate                      274
#define cWorkEndDate                        275
#define cWorkType                           276
#define cWorkingDayCalendarID               277
#define cWorkingDayCalendarKey              278
#define cWorkingDays                        279
#define cYear                               280
#define cZipCode                            281
#define cZoneID                             282
#define cZoneKey                            283
#define cZoneTypeID                         284
#define cZoneTypeKey                        285

/* This value is returned when a table or column string cannot
   be found in the metabase. */
#define COLID_ERROR 0xffff


/*
 * ItiColIsColInTable returns TRUE if the given column is in the
 * specified table.
 *
 * Parameters: pszTableName      The name of the table.  This
 *                               parameter may be NULL if usTable is
 *                               used.
 *
 */

extern BOOL EXPORT ItiColIsColInTable (PSZ    pszTableName,
                                       USHORT usTable,
                                       PSZ    pszColumn,
                                       USHORT usColumn);


/*
 * ItiColStringToColId returns a column ID for a given column name.
 */

extern USHORT EXPORT ItiColStringToColId (PSZ pszCol);



/*
 * ItiColColIdToString returns pointer to a string for a given column ID.
 */

extern PSZ EXPORT ItiColColIdToString (USHORT usCol);



/*
 * ItiColStringToTableId returns a table ID for a given table name.
 */

extern USHORT EXPORT ItiColStringToTableId (PSZ pszTable);



/*
 * ItiColTableIdToString returns pointer to a string for a given table ID.
 */

extern PSZ EXPORT ItiColTableIdToString (USHORT usTable);


extern BOOL EXPORT ItiColInitialize (void); 




/*
 * ItiColGetDefaultValue returns a pointer to a string that
 * is the default value of the specified field.  If an invalid
 * table or column is given, NULL is returned.
 */

extern PSZ EXPORT ItiColGetDefaultValue (PSZ    pszTableName,
                                         USHORT usTable,
                                         PSZ    pszColumn,
                                         USHORT usColumn);
